### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by sevimcengiz** [sevimcengiz/Oryx-MRSI#1]
![logo](https://user-images.githubusercontent.com/5468765/108315274-9c0c7680-71d4-11eb-9040-7e6248ea55b8.png)

**Comment by agahkarakuzu** [comment]
![](https://static.wikia.nocookie.net/naturerules1/images/8/84/Plains-game-arabian-oryx-rhino-lion-nature-reserve-featured.jpg/revision/latest?cb=20190707014345)

**Comment by sevimcengiz** [comment]
![842CCE9E-DB77-4E64-9EB1-6517644B0F86](https://user-images.githubusercontent.com/5468765/118074582-46a0c980-b3bf-11eb-961b-83e7f6fe4064.jpeg)
Agah, What do you think about this?  👯‍♀️
